### ISSUE TITLE
Odovzdat prepis uvodneho stretnutia

### ISSUE THREAD

**Issue by zemko18** [TIS2019-FMFI/hladanie-ohlasov#1]
Je potrebné prepísať (Adam), poslať p. Petrovičovi záznam z našeho úvodneho stretnutia so zadávateľmi.

**Comment by valentovic5** [comment]
[Prepis.pdf](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3698910/Prepis.pdf)

**Comment by pavelpetrovic** [comment]
vdaka, tesim sa! hlavne to poslite tym pracovnickam z kniznice, s ktorymi ste boli na stretnuti, aby to skontrolovali a pripadne doplnili/poopravili.
