### ISSUE TITLE
Scopus a WoS praca s API

### ISSUE THREAD

**Issue by zemko18** [TIS2019-FMFI/hladanie-ohlasov#10]
budeme sem davat uzitocne linky a poznatky dokym sa nenaucime s tym poriadne pracovat

**Comment by zemko18** [comment]
s @valentovic5  skusame ako na Scopus Api,

toto je priklad funkcneho dopytu, pre ktory sme si ziskali API KEY, zadali nejaku querry a dostali to ako JSON subor: 

https://api.elsevier.com/content/search/scopus?apiKey=44fdb9e958f510cf4ca02070959d8fec&query=Zemko&httpAccept=application/json

uzitocne linky: 

https://dev.elsevier.com/tecdoc_search_request.html?fbclid=IwAR0prQwae38UVTCtjnKGHgwh6sPrjS_Jakx-ijJc2clOpKXONY-q5jm9x6A

**Comment by valentovic5** [comment]
> s @valentovic5 skusame ako na Scopus Api,
> 
> toto je priklad funkcneho dopytu, pre ktory sme si ziskali API KEY, zadali nejaku querry a dostali to ako JSON subor:
> 
> https://api.elsevier.com/content/search/scopus?apiKey=44fdb9e958f510cf4ca02070959d8fec&query=Zemko&httpAccept=application/json
> 
> uzitocne linky:
> 
> https://dev.elsevier.com/tecdoc_search_request.html?fbclid=IwAR0prQwae38UVTCtjnKGHgwh6sPrjS_Jakx-ijJc2clOpKXONY-q5jm9x6A

k tomu príkladu, ten kľúč (apiKey v http GET requeste) teraz nebude fungovať, pretože som ho vymazal, ale vieme vytvoriť kľúčov koľko bude treba :key:
