### ISSUE TITLE
Vytvoriť GUI mockup

### ISSUE THREAD

**Issue by valentovic5** [TIS2019-FMFI/hladanie-ohlasov#11]

**Comment by valentovic5** [comment]
![Snímka obrazovky z 2019-10-27 22-32-02](https://user-images.githubusercontent.com/47821635/67642461-4a1f4d80-f90c-11e9-835b-57ebdea8c6f6.png)
![Snímka obrazovky z 2019-10-27 22-32-33](https://user-images.githubusercontent.com/47821635/67642462-4a1f4d80-f90c-11e9-9bef-d3a04a8f53e8.png)
![Snímka obrazovky z 2019-10-27 22-33-50](https://user-images.githubusercontent.com/47821635/67642463-4a1f4d80-f90c-11e9-913c-68748c16e388.png)

**Comment by valentovic5** [comment]
### Úvodný formulár
V prípade vyhľadávania nie podľa DOI:
![Snímka obrazovky z 2019-11-03 20-38-07](https://user-images.githubusercontent.com/47821635/68093593-9122bb00-fe97-11e9-9829-9c4fc89def5a.png)
![Snímka obrazovky z 2019-11-03 20-32-09](https://user-images.githubusercontent.com/47821635/68093627-eb238080-fe97-11e9-92cf-3fb159fb5cce.png)

V prípade vyhľadávania podľa DOI:
![Snímka obrazovky z 2019-11-03 20-38-43](https://user-images.githubusercontent.com/47821635/68093630-f24a8e80-fe97-11e9-9700-5c2bac509f95.png)

**Comment by valentovic5** [comment]
### Nájdené Záznamy (Zoznam Prác)
![Snímka obrazovky z 2019-11-03 23-30-15](https://user-images.githubusercontent.com/47821635/68093646-18702e80-fe98-11e9-9b21-020f94f20128.png)

**Comment by valentovic5** [comment]
### Nájdené Zoznamy Citácií
![Snímka obrazovky z 2019-11-04 00-06-54](https://user-images.githubusercontent.com/47821635/68093659-3342a300-fe98-11e9-928d-9c6cc65d9ad5.png)

**Comment by pavelpetrovic** [comment]
pekne. uz ste vsetci stotozneni s tym, ze to takto ma vyzerat? skontroloval to niekto?
ak hej, tak potom este, prosim, zajdite za ludmi, ktori to maju pouzivat a presne a podrobne im vysvetlite na tychto obrazkoch ako to bude fungovat a opytajte sa, ci je to takto v poriadku. potom az zatvorte tento issue. dakujem.

**Comment by pavelpetrovic** [comment]
prosim upravit do finalnej podoby a potom osobne prekonzultovat s nejakymi zadavatelmi

**Comment by valentovic5** [comment]
> ### Nájdené Záznamy (Zoznam Prác)
> ![Snímka obrazovky z 2019-11-03 23-30-15](https://user-images.githubusercontent.com/47821635/68093646-18702e80-fe98-11e9-9b21-020f94f20128.png)

OPRAVA!:
![68093646-18702e80-fe98-11e9-9b21-020f94f20128](https://user-images.githubusercontent.com/47821635/69039430-325b5680-09ec-11ea-9c92-4f807b6e1c8e.png)

**Comment by valentovic5** [comment]
GUI mockup bol dohodnutý so zadávateľom.
Dohodli sme sa na zvýraznení zaškrtnutých citácií v nájdených záznamoch (posledný obrázok) až po kliknutí na tlačidlo "vyhľadaj citácie".

Nájdené záznamy majú vyzerať (obsahovať údaje) tak, ako v pôvodnej aplikácii (https://sluzby.fmph.uniba.sk/ka/citacie/).
vzorový záznam (z pôvodnej aplikácie):
<img width="588" alt="Vzorový Záznam " src="https://user-images.githubusercontent.com/47821635/69143028-55f3cf00-0ac8-11ea-80ac-70bfb93d56b1.PNG">

Nájdené zoznamy citácií majú tiež vyzerať tak ako v pôvodnej aplikácii.
vzorový zoznam citácií:
<img width="501" alt="Vzorový Zoznam Citácií k práci" src="https://user-images.githubusercontent.com/47821635/69144706-2777f300-0acc-11ea-827a-1d6b1675e257.PNG">
