### ISSUE TITLE
Testovacie scenáre

### ISSUE THREAD

**Issue by zemko18** [TIS2019-FMFI/hladanie-ohlasov#13]
Na Githube je dokument s testovacími scenármi - ktorý vznikne podľa Katalógu požiadaviek. Jeden scenár môže testovať aj viacero požiadaviek, ale každá požiadavka z katalógu musí byť kompletne pokrytá v nejakom testovacom scenári.

**Comment by zemko18** [comment]
[Testovacie_scenare.pdf](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3856142/Testovacie_scenare.pdf)

**Comment by pavelpetrovic** [comment]
pridat prosim riadok predpoklady ku kazdemu scenaru
ak je niektory scenar vykonvavany viackrat, z roznych situacii a pod. tak to tam uvedte.

**Comment by zemko18** [comment]
[Testovacie_scenare.pdf](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3884121/Testovacie_scenare.pdf)
