### ISSUE TITLE
state diagram (UML)

### ISSUE THREAD

**Issue by zemko18** [TIS2019-FMFI/hladanie-ohlasov#14]
state diagram

**Comment by zemko18** [comment]
![state_v1](https://user-images.githubusercontent.com/36670319/68544315-2525e280-03c2-11ea-98f8-2708614807fe.png)

[Untitled Diagram.zip](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3828443/Untitled.Diagram.zip)

prvotna verzia state diagramu, v zipe je subor pre stranku draw.io, tam sa to da hocikedy zmenit

**Comment by pavelpetrovic** [comment]
pekne. preco sa to vola hladanie autorov? nemalo by to byt hladanie publikacii?
neda sa hladat publikacie znovu potom, co sa vyhladali citacie - musi sa najskor zatvorit aplikacia?

**Comment by zemko18** [comment]
![state_v2](https://user-images.githubusercontent.com/36670319/68549897-d39b4900-03fd-11ea-85c0-8361ce8d20ef.png)

dufam, ze som spravne zapracoval vase pripomienky

**Comment by zemko18** [comment]
![state_v3](https://user-images.githubusercontent.com/36670319/69014721-900c8600-098d-11ea-8430-5b04860622ae.png)
pridanie autentifikacie a mala zmena nazvov

**Comment by pavelpetrovic** [comment]
aktualny diagram obsahuje stavy, ktore nie su spravne popisane, nezodpovedaju stavom gui
jedna moznost je nahradit cely makrostav vyhladavanie publikacii jednym stavom

"zobrazeny formular atributov vyhladvania"
z ktoreho stavovy prechod "potvrdenie vyberu atributov pouzivatelom"
vedie do stavu "caka sa na vysledky" odtial po prijati vysledkov "zobrazene publikacie" a odtial po naklikani vybratych publikacii (akcia, ktora vedie do toho isteho stavu) a potvrdeni (akcia do dalsieho stavu) ide do stavu "caka sa na vysledky" odtial cez stavovy prechod "prisiel prvy vysledok" do stavu "zobrazene ciastkove vysledky"  (kde uz je stavovy prechod do toho isteho stavu cez "kopirovanie cit.stringu") a odtial cez prechod "prisli posledne vysledky" do stavu "zobrazene vsetky vysledky"...

**Comment by zemko18** [comment]
![state](https://user-images.githubusercontent.com/36670319/69500038-e894d380-0ef7-11ea-8859-7902c6b3b98e.png)

diagram zobrazuje stavy GUI, z kazdeho stavu sa da ist na zaciatok ale pre prehladnost som to tam nezakreslil
