### ISSUE TITLE
Vytvoriť katalóg požiadaviek

### ISSUE THREAD

**Issue by zemko18** [TIS2019-FMFI/hladanie-ohlasov#2]

**Comment by pavelpetrovic** [comment]
S najdenim dokumentacie na pristup do citacnych databaz Vam poradi pani Ilavska z rektoratu, kontakt: jana.ilavska@uniba.sk

**Comment by pavelpetrovic** [comment]
* zadany bol p.Gersovou
* funkcionalita bude realizovaná pomocou webovej aplikácie - iba?
   -> malo by sa prejavit aj v casti 3
* wos api?
* 2.1. chyba mi informacia o UK, resp. o tom, ze by to malo byt pre vsetky fakulty
* 2.2. zodpovedajuce publikacie? co to je?
       rok publikacie - rozsah?
       Tento zoradený zoznam - citovane? názov citujúcej publikácie
* 2.3. opisat pouzivatelsku rolu ako taku, to co je tam teraz presunte do 2.1

* v poz. 4 prosim upresnit, ze sa matchuje iba podla DOI alebo podla uplnej zhody
  ale co ak niektore polia su vyplnene v jednom a v druhom nie a pod...

ocislovanie poziadaviek 4.* nezodpoveda logike

* 4.3. mozete vylepsit tym, ze autocitacie su zobrazitelne nejakym sposobom
* 4.4. podla mna deduplikovanie sa vztahuje na to, ze sa publikacie najdu 
       v oboch databazach - skontrolujte si to u zadavatela
* v 4.5. uviest presne ktore udaje su potrebne a maju byt oznacovane ako chybajuce
* v 4.6 prosim upresnit format udajov o citacii (ktore pole Marc21 a aky je interny
   format informacie o citacii) - skonfrontujte s informaciami od p.Ilavskej
* 4.7. prosim vysvetlit, ze ide o ulohu, ktoru musi robit aplikacia (konvertovat kapitalizaciu pismen)

urcite doplnte podrobnu specifikaciu formatu, alebo odkaz na dokument, kde je vysvetlena

* uvedte co bude robit copy, ak niektore polozky chybaju  
* v ramci technickych moznosti a obmedzeni API sa vysledky budu zobrazovat priebezne, 
ale zobrazene vysledky uz budu finalne a nemenne

**Comment by zemko18** [comment]
[Katalog_poziadaviek-v2.docx](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3739026/Katalog_poziadaviek-v2.docx)

upravena verzia katalogu

**Comment by pavelpetrovic** [comment]
najvyssi cas skontrolovat, ci oba systemy ponukaju vsetko, co potrebujete a viete to najst
--
dokument miesa anglictinu v nadpisoch s textom v slovencine
v 2.2. mi chyba moznost vyberu publikacii, ku ktorym sa budu hladat ohlasy a potom aj sposob ich zobrazenia bude mozno trochu iny (?)
3 - 2. poz.:  domysliet, ci proces nebude dvojfazovy - najskor iba publikacia a potom k nim k vybranym ich citacie
poziadavky treba rozbit na atomicke, zatial su prilis kombinovane
prva cast mozno nemusi byt postupne, lebo je to asi len jeden request (?)
prave v casti 6 by som cakal postpne zobrazovanie
v 8 by som skor ocakaval popis struktury - ze vysledok je zoznam citovanych a pod kazdou citovanou je zoznam citujucich
do 12 by som uviedol, ze system v tejto verzii

**Comment by valentovic5** [comment]
@pavelpetrovic , posielam upravenu verziu katalógu požiadaviek:

pdf:
[KatalogPoziadaviek_verzia3.pdf](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3763680/KatalogPoziadaviek_verzia3.pdf)

tex:  (na GitHub mi nešlo odovzdať .tex súbor, tak som ho premenoval na .txt):
[KatalogPoziadaviek_verzia3.txt](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3763686/KatalogPoziadaviek_verzia3.txt)

**Comment by pavelpetrovic** [comment]
- mozete si opravit dlzen "poctu citacii."
- v 2.2 "dalsie informacie" asi chcete upresnit, ze ide o citacie, ci?
- 2.4 a 2.5 - pohladavky? :} viete, co to slovo znamena?
- 3.1 - nerozumiem, preco je checkbox za mnozinou rokov? niekto moze mat aj 20 publikacii v tom istom roku - tie nie je mozne hladat na pozadi?
 - 3.2. zoznamy - zaznamy
 - 3.8.7 nerozumim, ci ku kazdej publikacii zvlast, alebo sucet pre vsetky zaskrtnute publikacie, alebo obidvoje?
 - 3.8.8 su vsetky tie
v texte ostalo este par syntaktickych preklepov.
opravte, prosim, tychto par drobnosti a ked to bude hotovo, rovno uz poslite dokument aj zadavatelom aj pani Ilavskej, aby si ho dokladne prestudovali a dali Vam spatnu vazbu, doplnili a navrhli upravy, lebo podla vyslednej verzie dokumentu system navrhnete a implementujete. dakujem.

**Comment by valentovic5** [comment]
Poznámka:
3.8.7 (Počty Nájdených Výsledkov) je pod-požiadavka požiadavky 3.8. (Zoznam Citácií na Prácu/Práce), a teda sa jedná o počty nájdených výsledkov zoznamu citácií na prácu/práce. Samozrejme tieto počty je možné aktualizovať aj pri postupnom zobrazovaní výsledkov (pri požiadavke 3.8.1 (Postupné Zobrazovanie Výsledkov)).

pdf:
[KatalogPoziadaviek_verzia4.pdf](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3774846/KatalogPoziadaviek_verzia4.pdf)

tex: (na GitHub mi nešlo odovzdať .tex súbor, tak som ho premenoval na .txt)
[KatalogPoziadaviek_verzia4.txt](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3774851/KatalogPoziadaviek_verzia4.txt)

**Comment by valentovic5** [comment]
Zahrnuté Požiadavky od pani Ilavskej
pdf:
[KatalogPoziadaviek_verzia5.pdf](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3802301/KatalogPoziadaviek_verzia5.pdf)

tex: (na GitHub mi nešlo odovzdať .tex súbor, tak som ho premenoval na .txt)
[KatalogPoziadaviek_verzia5.txt](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3802305/KatalogPoziadaviek_verzia5.txt)

**Comment by pavelpetrovic** [comment]
- toto: "System bude dostupny len pre pouzivatel'ov, ktori pristupuju z IP adries, ktore maju platne licencie do databaz, ktore system vyuziva." nevzniklo nahodou tak, ze mala zadavatelka pocit, ze dopyty sa deju priamo z pocitacov pouzivatelov? ak budu dopyty robene zo servra, tak staci, aby server mal taku IP adresu. Ak to napriek tomu ma platit, tak potom budete musiet overovat IP adresy, o com vsak v KP nie je reci (v takom pripade to treba doplnit). Moj navrh - upravte to na IP adresu servra. Zrejme ide o to, ze trebars fakulta mediciny moze mat na svoje IP adresy predplatne na ine databazy ako matfyz. Ak je to tak, tak si to budu musiet nainstalovat na svoj server.

- chronicky notorik: "checkbox hl'adaj na pozadi" - bude teda hned na uvodnom formulari, alebo az, ked vypadnu clanky a hladaju sa citacie?? (prosim opravit)

- 3.4.2 v akej zatvorke? o com je rec?, odkazte sa, prosim, na 3.2.1 aby to bolo jednoznacne, co myslite.

-3.4.2.2. "je" - "je" 

- 3.9.4 dajte sem, prosim, krizovy odkaz na 3.10.1. dakujem.

- 3.9.6. hovori tato poziadavka o niecom? ak nie, tak ju dajte prec. (podla mna je to redundantne vzhladom na to, co uz je napisane v 3.9, ale mozno som len nepochopil)

- 3.9.7.1 a 3.9.7.2 sa odlisuju ako? nie je to jasne, prosim, vysvetlit.

**Comment by valentovic5** [comment]
pdf:
[KatalogPoziadaviek_verzia6.pdf](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3809100/KatalogPoziadaviek_verzia6.pdf)

tex: (na GitHub mi nešlo odovzdať .tex súbor, tak som ho premenoval na .txt)
[KatalogPoziadaviek_verzia6.txt](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3809103/KatalogPoziadaviek_verzia6.txt)

zoznam zmien (medzi verziou 5 a 6):
[ZoznamZmien.txt](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3809105/ZoznamZmien.txt)

**Comment by zemko18** [comment]
katalog je potvrdeny a schvaleny od pani Ilavskej, teda verzia6 plati

**Comment by zemko18** [comment]
![suhlasIL](https://user-images.githubusercontent.com/36670319/69013775-2471eb00-0984-11ea-8c4f-5baede28479c.png)
![suhlasME](https://user-images.githubusercontent.com/36670319/69013776-2471eb00-0984-11ea-804e-151ffffff586.png)


iba pridavam suhlasy na KP
