### ISSUE TITLE
Zahrnúť do prepisu úvodného stretnutia so zadávateľom pripomienky od zadávateľa.

### ISSUE THREAD

**Issue by valentovic5** [TIS2019-FMFI/hladanie-ohlasov#3]

**Comment by valentovic5** [comment]
[Prepis.pdf](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3708477/Prepis.pdf)

**Comment by valentovic5** [comment]
Poprosím o zaslanie zadávateľovi, ďakujem :).

**Comment by zemko18** [comment]
Poslane, cakam na odpoved.
