### ISSUE TITLE
Vytvorenie návrhu

### ISSUE THREAD

**Issue by TomassMa** [TIS2019-FMFI/hladanie-ohlasov#4]
A. podrobná špecifikácia vonkajších interfejsov - ak aplikácia komunikuje s inými aplikáciami, súbormi, zariadeniami - tieto musia byť jasne a podrobne definované
B. podrobný dátový model perzistentných údajov, formátov súborov, komunikačných protokolov.
C. návrh používateľského rozhrania (ak projekt má GUI) - nakreslené a popísané všetky dialógy, okná a stránky, ktorými aplikácia komunikuje s používateľom - túto časť treba konzultovať so zadávateľom
D. Zrozumiteľný a jednoznačný návrh implementácie, podľa ktorého sa dá aplikácia vyvinúť a ktorý bude obsahovať: UML component diagram, UML class diagram, a aspoň jeden z dvojice UML state a UML sequence diagram, zrozumiteľne vysvetlenú architektúru, rozdelenie na časti (moduly) a ich interfejsy, využité technológie, cieľové prostredie nasadenia do prevádzky.

**Comment by NorbertJu** [comment]
[Navrh.pdf](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3884208/Navrh.pdf)
Prva verzia skompletizovaneho navrhu

**Comment by pavelpetrovic** [comment]
komponentny:
- gulicky
- priame prepojenie comunicator s oboma searchami

stavovy:
 - info missing: ktora entita
 - kazdy stavovy prechod musi mat popis (aut ->form1)
 - sipocka naopak
 - pridat prosim aj cyklicke sipky

triedny:
 - rozdelit showResultList() na dva
 - sendQuery asi tiez na dva
 - zvazte, ci neoplati sa typ "Publikacia"  a  "Citacia", ktore budu udrzovat informacie, prijdene zo servra, z ktorych gui-ckove okienka vyrenderuju obsah, potom by sme mohli zoznam "vybratych" objektov publikacia rovno poslat do druheho okna s citaciami a este kym ani nic neprislo, hned moze byt zoznam publikacii, pre ktore sa hladaju citacie, zobrazeny
https://stackoverflow.com/questions/87359/can-i-pass-a-javascript-variable-to-another-browser-window

- na serveri zvazit pridat triedu Settings (nacita z konfigu)
- triedy publication, citation mozu byt zdielane medzi klientom serverom
- mohla by pribudnut trieda Client na servri, ktora udrzuje informacie o pripojenom klientovi, zoznam jeho zobrazenych publikacii a stav posielania citacii (?), minimalne referenciu na jeho "socket"

ostava rozpisat zoznam tried a ich metod aj s argumentami a kratkym popisom, co robia, podla toho si rozdelit ulohy

**Comment by zemko18** [comment]
![stavovy](https://user-images.githubusercontent.com/36670319/69948294-a79c5080-14ef-11ea-8ab1-5b425f5b0f4c.png)
![komponent](https://user-images.githubusercontent.com/36670319/69948295-a79c5080-14ef-11ea-8893-ffe7c48c7f9f.png)

**Comment by TomassMa** [comment]
Server 
![image](https://user-images.githubusercontent.com/55876812/69958974-4e8be700-1506-11ea-9122-629aa3fe6a41.png)
Klient
![image](https://user-images.githubusercontent.com/55876812/69958995-59df1280-1506-11ea-8c44-19c29f09df1d.png)

**Comment by zemko18** [comment]
[Navrh.pdf](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3936678/Navrh.pdf)

pridane zmenene diagramy
