### ISSUE TITLE
špecifiacia vonkajších intefejsov

### ISSUE THREAD

**Issue by zemko18** [TIS2019-FMFI/hladanie-ohlasov#6]

**Comment by zemko18** [comment]
špecifikácia interfejsov

**Comment by zemko18** [comment]
[Hľadanie ohlasov - navrh A.docx](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3774726/Hladanie.ohlasov.-.navrh.A.docx)

prilozeny subor je prva cast navrhu, v pripadne pripomienok od @pavelpetrovic ich co najskor zapracujem nech sa pracuje na dalsich castiach navrhu.

**Comment by valentovic5** [comment]
Nebolo by lepšie toto: https://spring.io/ ?

**Comment by pavelpetrovic** [comment]
spring si vyzaduje aplikacny server a je to velmi komplexny system.
ak ste v tom este nerobili a naopak ak ste robili v Laraveli, tak odporucam radsej ten Laravel, ale tato aplikacia je malicka a moj nazor je, ze nepotrebuje ziaden framework. je to ale len na Vas. 
k dokumentu: k HTML, CSS, Javascript, PHP netreba robit samostatne casti, staci jedna veta, ze tieto technologie pouzijete. Naopak, to Scopus a WOS API treba rozpisat co najpodrobnejsie, ako to budete pouzivat, aby ste to podla tohto dokumentu vedeli naprogramovat. 
Ak framework, tak by tam tiez malo byt vysvetlene, ake nasledky to pre navrh a vyvoj systemu bude mat.

**Comment by zemko18** [comment]
[Hľadanie ohlasov - navrh A.docx](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3802016/Hladanie.ohlasov.-.navrh.A.docx)

upravena verzia v ktorej je NodeJS a JS, scopus a api som nerozpisoval viac, na scopus je vytvorene pdf, ktore najdete v: https://github.com/TIS2019-FMFI/hladanie-ohlasov/issues/7

na podobnom subore pre WOS sa pracuje
