### ISSUE TITLE
Návrh časť B

### ISSUE THREAD

**Issue by zemko18** [TIS2019-FMFI/hladanie-ohlasov#7]

**Comment by zemko18** [comment]
dátový model

**Comment by NorbertJu** [comment]
[data_model.pdf](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3776337/data_model.pdf)
Prilozeny datovy, resp. domenovy model, vytvoreny na zaklade scopus api response.

**Comment by pavelpetrovic** [comment]
je to asi dobry zaklad pre triedny diagram...   
tiez tieto udaje asi budu putovat zo servra na klienta, takze aj pre interny komunikacny protokol a rozhrania medzi komponentnami
(asi nejaky json?)

**Comment by NorbertJu** [comment]
[Scopus communication protocol.pdf](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3801968/Scopus.communication.protocol.pdf)
Prilozeny komunikacny protokol pre pracu s databazou Scopus cez API rozhranie.

**Comment by TomassMa** [comment]
[WOS API.pdf](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3802201/WOS.API.pdf) - Komunikačný protokol WOS verzia 1
