### ISSUE TITLE
Návrh časť D

### ISSUE THREAD

**Issue by zemko18** [TIS2019-FMFI/hladanie-ohlasov#9]

**Comment by zemko18** [comment]
Zrozumiteľný a jednoznačný návrh implementácie

**Comment by TomassMa** [comment]
![Class](https://user-images.githubusercontent.com/55876812/68551142-0cd9b600-040a-11ea-8a6b-c5b72dad8abf.jpg)

**Comment by NorbertJu** [comment]
[Popis.Architektury.docx](https://github.com/TIS2019-FMFI/hladanie-ohlasov/files/3857209/Popis.Architektury.docx)
Aktualna verzia, aj so serverovov castou.

**Comment by TomassMa** [comment]
Klient - Triedny Diagram
![image](https://user-images.githubusercontent.com/55876812/69066534-bf6cd280-0a21-11ea-816d-f0df73cfa51f.png)

**Comment by TomassMa** [comment]
Server - triedny diagram
![image](https://user-images.githubusercontent.com/55876812/69066591-d3b0cf80-0a21-11ea-83d6-98cbc265ff19.png)

**Comment by zemko18** [comment]
klient nema mat translator, pridat komunikator

server pridat komunikator, spojit translator a interface

**Comment by TomassMa** [comment]
Klient - Triedny diagram
![image](https://user-images.githubusercontent.com/55876812/69186768-84e66100-0b19-11ea-9754-326c37509ba4.png)
Server - Triedny diagram
![image](https://user-images.githubusercontent.com/55876812/69186876-ba8b4a00-0b19-11ea-8dba-dbc5468adaba.png)
